# Generated by Django 4.2.7 on 2023-11-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_attendance_client_commission_routeplan_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_vendor',
        ),
        migrations.DeleteModel(
            name='ManagementAdmin',
        ),
    ]
